site_name: Adrs-docs
site_description: Digital Backbone Feature Specification
nav:
  - Adoption of Lightweight ADRs: KDR-001.md
  - Adoption of a Canonical Data Model: KDR-002.md
plugins:
  - techdocs-core
